# This is a basic workflow to help you get started with Actions
name: Publish API Catalogs to Exchange

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # Build Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install api-catalog cli
        run: |
          sudo apt-get update
          npm install -g api-catalog-cli@latest
      - name: Publish API to Anypoint Exchange
        env: 
          ANYPOINT_CLIENTID: 3f8c14f6b59e4498a3b2f8007f9d0041
          ANYPOINT_CLIENTSECRET: 605F069E76CE454FAfAED74F234b6F83
          ANYPOINT_ORG_ID: ba9e1c6d-a9e2-4787-a36e-aae7ea9c5595
        run: |
          api-catalog publish-asset --organization="$ANYPOINT_ORG_ID" --client_id="$ANYPOINT_CLIENTID" --client_secret="$ANYPOINT_CLIENTSECRET"
